// webpack.config.js
// 自定义 loader 演示：
//   1) banner-loader  -> 在每个匹配文件顶部插入注释 banner
//   2) replace-loader -> 把代码中的某些字符串替换成另一个
//   3) txt-loader     -> 把 .txt 文件作为字符串导出（默认 raw-loader 行为）
// 通过 resolveLoader.modules 让 webpack 能从本地 ./loaders 目录解析自定义 loader
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = (env, argv) => {
  const mode = argv.mode || "development";
  return {
    mode,
    entry: "./src/index.js",
    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "js/bundle.[contenthash:8].js",
      clean: true,
    },
    // 关键：让 webpack 解析 loader 时除了 node_modules 之外，还从本地 loaders 目录找
    resolveLoader: {
      modules: ["node_modules", path.resolve(__dirname, "loaders")],
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: [
            // loader 执行顺序：从下往上，从右往左
            // 因此先 replace 后 banner，最终顶部出现 banner
            {
              loader: "banner-loader",
              options: {
                text: "Auto-generated by custom banner-loader",
                author: "demo",
              },
            },
            {
              loader: "replace-loader",
              options: {
                rules: [
                  {
                    search: "__GREETING__",
                    replace: '"Hello from custom loader!"',
                  },
                ],
              },
            },
          ],
        },
        {
          test: /\.txt$/,
          use: ["txt-loader"],
        },
      ],
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: "./public/index.html",
        title: "自定义 loader Demo",
      }),
    ],
    devServer: {
      port: 8093,
      open: true,
      hot: true,
    },
  };
};
